version: "3"
services:
  web:
    image: morteb43/moonshot:latest
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgres://postgres:postgres@db/react_rails_api_project_template_production"
    ports:
      - "88:3000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: react_rails_api_project_template_production
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: