version: "3"
services:
  web:
    image: morteb43/moonshot:latest
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgres://postgres:password@db/react_rails_api_project_template_production"
    ports:
      - "88:3000"
    depends_on:
      - db
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: react_rails_api_project_template_production
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: