version: "3"
services:
  web:
    image: morteb43/moonshot:latest
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: db
    networks:
      - internal_network
    ports:
      - "88:3000"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: always
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: react_rails_api_project_template_production
    networks:
      - internal_network
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: