# Use the Ruby Alpine image as the base image
FROM ruby:2.7-alpine

# Install build dependencies
RUN apk add --update --no-cache \
  build-base \
  postgresql-dev \
  nodejs \
  yarn \
  tzdata

# Set the working directory
WORKDIR /app

# Copy the Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock ./

# Install bundler
RUN gem install bundler:2.3.22

# Install gems
RUN bundle install

# Copy the application code
COPY . .

# Expose the port
EXPOSE 3000

# Set the command to run the puma server
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]