version: "3"
services:
  web:
    image: morteb43/moonshot:latest
    environment:
      RAILS_ENV: production
      DATABASE_URL: "postgres://postgres:password@db/react_rails_api_project_template_production"
    ports:
      - "80:3000"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: react_rails_api_project_template_production
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
volumes:
  db_data: