name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile-rails --tag us-west1-docker.pkg.dev/corded-observer-300301/moonshot/moonshot-rails:$(date +%s)
        docker build . --file Dockerfile-postgres --tag us-west1-docker.pkg.dev/corded-observer-300301/moonshot/moonshot-postgres:$(date +%s)
