name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      env:
        GCP_PROJECT_ID: your-project-id
        GCP_REGION: your-region
        GCP_REGISTRY: your-registry
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
        gcloud config set project ${GCP_PROJECT_ID}
        gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile-rails --tag ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REGISTRY}/moonshot-rails:$(date +%s)
        docker push ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REGISTRY}/moonshot-rails:$(date +%s)
