name: Build Docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          bundle install
          cd client
          npm install

      - name: Build frontend
        run: |
          cd client
          npm run build

      - name: Build Docker image
        run: |
          docker build -t nicmortelliti/moonshot:latest .
          docker login -u nicmortelliti -p ${{ secrets.DOCKER_PASSWORD }}
          docker push nicmortelliti/moonshot:latest
